[supervisord]
nodaemon=true
user=root
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[program:web]
command=/usr/local/bin/cognitrix --ui web
priority=10
autostart=true
autorestart=unexpected
startsecs=2
stopsignal=TERM
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:worker]
command=/usr/local/bin/python -m celery -A cognitrix.celery_worker worker --pool=solo --loglevel=info
priority=10
autostart=true
autorestart=unexpected
startsecs=2
stopsignal=TERM
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
